import { createGlobalTheme } from '@vanilla-extract/css'

export const vars = createGlobalTheme(':root', {
  fontFamily: {
    inter: 'var(--text-font-family-inter)',
  },
  fontSize: {
    xs: 'var(--text-font-size-xs)',
    sm: 'var(--text-font-size-sm)',
    md: 'var(--text-font-size-md)',
    lg: 'var(--text-font-size-lg)',
    xl: 'var(--text-font-size-xl)',
    '2xl': 'var(--text-font-size-2xl)',
    '3xl': 'var(--text-font-size-3xl)',
  },
  lineHeight: {
    xs: 'var(--text-line-height-xs)',
    sm: 'var(--text-line-height-sm)',
    md: 'var(--text-line-height-md)',
    lg: 'var(--text-line-height-lg)',
    xl: 'var(--text-line-height-xl)',
    '2xl': 'var(--text-line-height-2xl)',
    '3xl': 'var(--text-line-height-3xl)',
  },
  fontWeight: {
    light: 'var(--text-font-weight-light)',
    regular: 'var(--text-font-weight-regular)',
    medium: 'var(--text-font-weight-medium)',
    'semi-bold': 'var(--text-font-weight-semi-bold)',
    bold: 'var(--text-font-weight-bold)',
  },
  color: {
    default: 'var(--text-color-default)',
    subtle: 'var(--text-color-subtle)',
    brand: 'var(--text-color-brand)',
    success: 'var(--text-color-success)',
    error: 'var(--text-color-error)',
  },
  scale: {
    '0': 'var(--scale-0)',
    '25': 'var(--scale-25)',
    '50': 'var(--scale-50)',
    '100': 'var(--scale-100)',
    '200': 'var(--scale-200)',
    '300': 'var(--scale-300)',
    '400': 'var(--scale-400)',
    '500': 'var(--scale-500)',
    '600': 'var(--scale-600)',
    '700': 'var(--scale-700)',
    '800': 'var(--scale-800)',
    '900': 'var(--scale-900)',
    '1000': 'var(--scale-1000)',
    '1100': 'var(--scale-1100)',
    '1200': 'var(--scale-1200)',
    '1300': 'var(--scale-1300)',
  },
})
